services:
    moonshiner.webresource:
        class: Moonshiner\BrigthenBundle\Services\ResourceInterface
    Moonshiner\BrigthenBundle\Security\User\UserProvider: ~
    Moonshiner\BrigthenBundle\Security\User\CustomerProvider: ~
    Moonshiner\BrigthenBundle\Service\Factory:
        true
